In [53]:
import os
import pandas as pd

In [54]:
base_dir = os.getcwd()
path_data = os.path.join(base_dir, '..', 'data', 'raw', 'Quina.csv')

df = pd.read_csv(path_data, sep=';')
df

      numero        data         dezenas
0          1  13/03/1994  25,45,60,76,79
1          2  17/03/1994  13,30,58,63,64
2          3  20/03/1994  05,15,32,33,48
3          4  24/03/1994  27,57,60,61,77
4          5  27/03/1994  19,44,53,54,71
...      ...         ...             ...
6940    6978  17/03/2026  09,10,26,44,72
6941    6979  18/03/2026  20,23,27,32,42
6942    6980  19/03/2026  07,08,66,76,80
6943    6981  20/03/2026  07,29,39,59,78
6944    6982  21/03/2026  21,25,26,42,46

[6945 rows x 3 columns]

# Feature engineering

- Criação de features para gerar insights e analises.

In [55]:
# Transformar a string na coluna de dezenas em lista de inteiros para realocar em colunas separadas
dezenas_split = df['dezenas'].str.split(',', expand=True) # O expand=True transforma a lista resultante em novas colunas automaticamente

# Renomear as colunas 
dezenas_split.columns = [f'bola_{i+1}' for i in range(dezenas_split.shape[1])]

for col in dezenas_split.columns:
    dezenas_split[col] =  pd.to_numeric(dezenas_split[col])
    
df_final = pd.concat([df, dezenas_split], axis=1)

df_final = df_final.drop(columns=['dezenas'])

df_final

      numero        data  bola_1  bola_2  bola_3  bola_4  bola_5
0          1  13/03/1994      25      45      60      76      79
1          2  17/03/1994      13      30      58      63      64
2          3  20/03/1994       5      15      32      33      48
3          4  24/03/1994      27      57      60      61      77
4          5  27/03/1994      19      44      53      54      71
...      ...         ...     ...     ...     ...     ...     ...
6940    6978  17/03/2026       9      10      26      44      72
6941    6979  18/03/2026      20      23      27      32      42
6942    6980  19/03/2026       7       8      66      76      80
6943    6981  20/03/2026       7      29      39      59      78
6944    6982  21/03/2026      21      25      26      42      46

[6945 rows x 7 columns]

In [56]:
# df_final['data'] = pd.to_datetime(df_final['data'], format='%d/%m/%Y')
# df_final['ano'] = df_final['data'].dt.year
# df_final['mes'] = df_final['data'].dt.month
# df_final['dia_semana'] = df_final['data'].dt.day_of_week
# df_final

### Features estatísticas

- Soma
- Média
- Amplitude
- Quantidade de pares e ímpares

In [62]:
colunas_bolas = [f'bola_{i+1}' for i in range(5)]

df_features = df_final.copy()

# Soma e Média: jogo foi mais 'alto' ou 'baixo'
df_features['soma'] = df_features[colunas_bolas].sum(axis=1)
df_features['media'] = df_features[colunas_bolas].mean(axis=1)
# Amplitude: Distância do maio para o menor número
df_features['amplitude'] = df_features[colunas_bolas].max(axis=1) - df_features[colunas_bolas].min(axis=1)
df_features['qtd_pares'] = df_features[colunas_bolas].apply(lambda x: sum(1 for n in x if n % 2 == 0), axis=1)
df_features['qtd_impares'] = 5 - df_features['qtd_pares']
 

df_features

,numero,data,bola_1,bola_2,bola_3,bola_4,bola_5,soma,media,amplitude,qtd_pares,qtd_impares
0,1,13/03/1994,25,45,60,76,79,285,57.0,54,2,3
1,2,17/03/1994,13,30,58,63,64,228,45.6,51,3,2
2,3,20/03/1994,5,15,32,33,48,133,26.6,43,2,3
3,4,24/03/1994,27,57,60,61,77,282,56.4,50,1,4
4,5,27/03/1994,19,44,53,54,71,241,48.2,52,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...
6940,6978,17/03/2026,9,10,26,44,72,161,32.2,63,4,1
6941,6979,18/03/2026,20,23,27,32,42,144,28.8,22,3,2
6942,6980,19/03/2026,7,8,66,76,80,237,47.4,73,4,1
6943,6981,20/03/2026,7,29,39,59,78,212,42.4,71,1,4
6944,6982,21/03/2026,21,25,26,42,46,160,32.0,25,3,2

### Feature de Lags, Distribuição de Quadrantes/Primos, Janelas Móveis, Adjacência

In [ ]:
df_roll_windows = df_features.copy()