In [23]:
import os
import pandas as pd

In [24]:
base_dir = os.getcwd()
path_data = os.path.join(base_dir, '..', 'data', 'raw', 'Quina.csv')

df = pd.read_csv(path_data)
df

      numero        data         dezenas
0          1  13/03/1994  25,45,60,76,79
1          2  17/03/1994  13,30,58,63,64
2          3  20/03/1994  05,15,32,33,48
3          4  24/03/1994  27,57,60,61,77
4          5  27/03/1994  19,44,53,54,71
...      ...         ...             ...
6940    6978  17/03/2026  09,10,26,44,72
6941    6979  18/03/2026  20,23,27,32,42
6942    6980  19/03/2026  07,08,66,76,80
6943    6981  20/03/2026  07,29,39,59,78
6944    6982  21/03/2026  21,25,26,42,46

[6945 rows x 3 columns]

In [25]:
df.to_csv('Quina.csv', sep=';', encoding='utf-8', index=False)

In [ ]:
df2 = pd.read_csv('Quina.csv', sep=';')
df2

      numero        data         dezenas
0          1  13/03/1994  25,45,60,76,79
1          2  17/03/1994  13,30,58,63,64
2          3  20/03/1994  05,15,32,33,48
3          4  24/03/1994  27,57,60,61,77
4          5  27/03/1994  19,44,53,54,71
...      ...         ...             ...
6940    6978  17/03/2026  09,10,26,44,72
6941    6979  18/03/2026  20,23,27,32,42
6942    6980  19/03/2026  07,08,66,76,80
6943    6981  20/03/2026  07,29,39,59,78
6944    6982  21/03/2026  21,25,26,42,46

[6945 rows x 3 columns]